// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: life_events.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLifeEvent = `-- name: CreateLifeEvent :one
INSERT INTO life_events (user_id, visa_id, event_type, occurred_at, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, visa_id, event_type, occurred_at, payload, created_at
`

type CreateLifeEventParams struct {
	UserID     int64           `json:"user_id"`
	VisaID     pgtype.Int8     `json:"visa_id"`
	EventType  string          `json:"event_type"`
	OccurredAt pgtype.Date     `json:"occurred_at"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) CreateLifeEvent(ctx context.Context, arg CreateLifeEventParams) (LifeEvent, error) {
	row := q.db.QueryRow(ctx, createLifeEvent,
		arg.UserID,
		arg.VisaID,
		arg.EventType,
		arg.OccurredAt,
		arg.Payload,
	)
	var i LifeEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaID,
		&i.EventType,
		&i.OccurredAt,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLifeEvent = `-- name: GetLifeEvent :one
SELECT id, user_id, visa_id, event_type, occurred_at, payload, created_at
FROM life_events
WHERE id = $1 AND user_id = $2
`

type GetLifeEventParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetLifeEvent(ctx context.Context, arg GetLifeEventParams) (LifeEvent, error) {
	row := q.db.QueryRow(ctx, getLifeEvent, arg.ID, arg.UserID)
	var i LifeEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaID,
		&i.EventType,
		&i.OccurredAt,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listLifeEventsForUser = `-- name: ListLifeEventsForUser :many
SELECT id, user_id, visa_id, event_type, occurred_at, payload, created_at
FROM life_events
WHERE user_id = $1
ORDER BY occurred_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListLifeEventsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLifeEventsForUser(ctx context.Context, arg ListLifeEventsForUserParams) ([]LifeEvent, error) {
	rows, err := q.db.Query(ctx, listLifeEventsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LifeEvent{}
	for rows.Next() {
		var i LifeEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VisaID,
			&i.EventType,
			&i.OccurredAt,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
