// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID                     int64              `json:"id"`
	UserID                 int64              `json:"user_id"`
	FullAddress            string             `json:"full_address"`
	PostalCode             pgtype.Text        `json:"postal_code"`
	Prefecture             pgtype.Text        `json:"prefecture"`
	City                   pgtype.Text        `json:"city"`
	Ward                   pgtype.Text        `json:"ward"`
	MovedInAt              pgtype.Date        `json:"moved_in_at"`
	MovedOutAt             pgtype.Date        `json:"moved_out_at"`
	RegisteredAtWardOffice bool               `json:"registered_at_ward_office"`
	WardOfficeName         pgtype.Text        `json:"ward_office_name"`
	IsCurrent              pgtype.Bool        `json:"is_current"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type ComplianceTask struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	VisaID             pgtype.Int8        `json:"visa_id"`
	RuleID             string             `json:"rule_id"`
	TriggeredByEventID pgtype.Int8        `json:"triggered_by_event_id"`
	TitleEn            string             `json:"title_en"`
	TitleJa            pgtype.Text        `json:"title_ja"`
	DescriptionEn      string             `json:"description_en"`
	DescriptionJa      pgtype.Text        `json:"description_ja"`
	Category           string             `json:"category"`
	Severity           string             `json:"severity"`
	Status             string             `json:"status"`
	DeadlineAt         pgtype.Date        `json:"deadline_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	LegalSourceUrl     pgtype.Text        `json:"legal_source_url"`
	LegalSourceText    pgtype.Text        `json:"legal_source_text"`
	LocationHint       pgtype.Text        `json:"location_hint"`
	Metadata           json.RawMessage    `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID                       int64              `json:"id"`
	UserID                   int64              `json:"user_id"`
	DocumentType             pgtype.Text        `json:"document_type"`
	StorageKey               string             `json:"storage_key"`
	OriginalFilename         pgtype.Text        `json:"original_filename"`
	MimeType                 pgtype.Text        `json:"mime_type"`
	FileSizeBytes            pgtype.Int8        `json:"file_size_bytes"`
	IssuingAuthority         pgtype.Text        `json:"issuing_authority"`
	IssuedAt                 pgtype.Date        `json:"issued_at"`
	ExpiresAt                pgtype.Date        `json:"expires_at"`
	OcrText                  pgtype.Text        `json:"ocr_text"`
	ParsedData               json.RawMessage    `json:"parsed_data"`
	SummaryEn                pgtype.Text        `json:"summary_en"`
	SummaryJa                pgtype.Text        `json:"summary_ja"`
	ClassificationConfidence pgtype.Float4      `json:"classification_confidence"`
	ParserVersion            pgtype.Text        `json:"parser_version"`
	UploadedAt               pgtype.Timestamptz `json:"uploaded_at"`
	ParsedAt                 pgtype.Timestamptz `json:"parsed_at"`
}

type DocumentTaskLink struct {
	DocumentID int64              `json:"document_id"`
	TaskID     int64              `json:"task_id"`
	LinkType   string             `json:"link_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Employer struct {
	ID                    int64              `json:"id"`
	UserID                int64              `json:"user_id"`
	Name                  string             `json:"name"`
	Address               pgtype.Text        `json:"address"`
	Role                  pgtype.Text        `json:"role"`
	EmploymentType        pgtype.Text        `json:"employment_type"`
	StartedAt             pgtype.Date        `json:"started_at"`
	EndedAt               pgtype.Date        `json:"ended_at"`
	ImmigrationNotifiedAt pgtype.Date        `json:"immigration_notified_at"`
	IsCurrent             pgtype.Bool        `json:"is_current"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type LifeEvent struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	VisaID     pgtype.Int8        `json:"visa_id"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Date        `json:"occurred_at"`
	Payload    json.RawMessage    `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	TaskID          int64              `json:"task_id"`
	FireAt          pgtype.Timestamptz `json:"fire_at"`
	ReminderType    string             `json:"reminder_type"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	DeliveryChannel pgtype.Text        `json:"delivery_channel"`
}

type TaskDependency struct {
	TaskID          int64 `json:"task_id"`
	DependsOnTaskID int64 `json:"depends_on_task_id"`
}

type User struct {
	ID          int64              `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	Locale      string             `json:"locale"`
	Timezone    string             `json:"timezone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Visa struct {
	ID                    int64              `json:"id"`
	UserID                int64              `json:"user_id"`
	VisaTypeCode          string             `json:"visa_type_code"`
	Status                string             `json:"status"`
	CoENumber             pgtype.Text        `json:"coe_number"`
	CoEIssuedAt           pgtype.Date        `json:"coe_issued_at"`
	LandedAt              pgtype.Date        `json:"landed_at"`
	ResidenceCardNumber   pgtype.Text        `json:"residence_card_number"`
	ResidenceCardIssuedAt pgtype.Date        `json:"residence_card_issued_at"`
	PeriodOfStayMonths    pgtype.Int4        `json:"period_of_stay_months"`
	ExpiresAt             pgtype.Date        `json:"expires_at"`
	SponsorName           pgtype.Text        `json:"sponsor_name"`
	SponsorAddress        pgtype.Text        `json:"sponsor_address"`
	JobTitle              pgtype.Text        `json:"job_title"`
	Notes                 pgtype.Text        `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type VisaType struct {
	Code          string `json:"code"`
	DisplayNameEn string `json:"display_name_en"`
	DisplayNameJa string `json:"display_name_ja"`
	RuleFile      string `json:"rule_file"`
}
