// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Inserts a generated task. Uses ON CONFLICT DO NOTHING because the schema
	// enforces idempotency via UNIQUE (user_id, rule_id, triggered_by_event_id).
	// If the task already exists, this returns no rows. The caller decides whether
	// that's a no-op or an error.
	CreateComplianceTask(ctx context.Context, arg CreateComplianceTaskParams) (ComplianceTask, error)
	CreateLifeEvent(ctx context.Context, arg CreateLifeEventParams) (LifeEvent, error)
	CreateVisa(ctx context.Context, arg CreateVisaParams) (Visa, error)
	// Returns the user's most relevant in-progress or active visa.
	// Order prefers active/landed status over planning/applied.
	GetActiveVisaForUser(ctx context.Context, userID int64) (Visa, error)
	GetComplianceTask(ctx context.Context, arg GetComplianceTaskParams) (ComplianceTask, error)
	GetLifeEvent(ctx context.Context, arg GetLifeEventParams) (LifeEvent, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetVisaByID(ctx context.Context, arg GetVisaByIDParams) (Visa, error)
	ListAllTasksForUser(ctx context.Context, userID int64) ([]ComplianceTask, error)
	ListLifeEventsForUser(ctx context.Context, arg ListLifeEventsForUserParams) ([]LifeEvent, error)
	ListPendingTasksForUser(ctx context.Context, userID int64) ([]ComplianceTask, error)
	// Returns tasks created by a specific life event. Used by the service layer
	// to return the freshly-generated tasks from RecordLifeEvent, so the HTTP
	// response can echo what was created without a follow-up query.
	ListTasksTriggeredByEvent(ctx context.Context, arg ListTasksTriggeredByEventParams) ([]ComplianceTask, error)
	ListVisasForUser(ctx context.Context, userID int64) ([]Visa, error)
	MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) (ComplianceTask, error)
}

var _ Querier = (*Queries)(nil)
