// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComplianceTask = `-- name: CreateComplianceTask :one
INSERT INTO compliance_tasks (
    user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, legal_source_url, legal_source_text, location_hint,
    metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15,
    $16
)
ON CONFLICT (user_id, rule_id, triggered_by_event_id) DO NOTHING
RETURNING id, user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, completed_at,
    legal_source_url, legal_source_text, location_hint,
    metadata, created_at, updated_at
`

type CreateComplianceTaskParams struct {
	UserID             int64           `json:"user_id"`
	VisaID             pgtype.Int8     `json:"visa_id"`
	RuleID             string          `json:"rule_id"`
	TriggeredByEventID pgtype.Int8     `json:"triggered_by_event_id"`
	TitleEn            string          `json:"title_en"`
	TitleJa            pgtype.Text     `json:"title_ja"`
	DescriptionEn      string          `json:"description_en"`
	DescriptionJa      pgtype.Text     `json:"description_ja"`
	Category           string          `json:"category"`
	Severity           string          `json:"severity"`
	Status             string          `json:"status"`
	DeadlineAt         pgtype.Date     `json:"deadline_at"`
	LegalSourceUrl     pgtype.Text     `json:"legal_source_url"`
	LegalSourceText    pgtype.Text     `json:"legal_source_text"`
	LocationHint       pgtype.Text     `json:"location_hint"`
	Metadata           json.RawMessage `json:"metadata"`
}

// Inserts a generated task. Uses ON CONFLICT DO NOTHING because the schema
// enforces idempotency via UNIQUE (user_id, rule_id, triggered_by_event_id).
// If the task already exists, this returns no rows. The caller decides whether
// that's a no-op or an error.
func (q *Queries) CreateComplianceTask(ctx context.Context, arg CreateComplianceTaskParams) (ComplianceTask, error) {
	row := q.db.QueryRow(ctx, createComplianceTask,
		arg.UserID,
		arg.VisaID,
		arg.RuleID,
		arg.TriggeredByEventID,
		arg.TitleEn,
		arg.TitleJa,
		arg.DescriptionEn,
		arg.DescriptionJa,
		arg.Category,
		arg.Severity,
		arg.Status,
		arg.DeadlineAt,
		arg.LegalSourceUrl,
		arg.LegalSourceText,
		arg.LocationHint,
		arg.Metadata,
	)
	var i ComplianceTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaID,
		&i.RuleID,
		&i.TriggeredByEventID,
		&i.TitleEn,
		&i.TitleJa,
		&i.DescriptionEn,
		&i.DescriptionJa,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.LegalSourceUrl,
		&i.LegalSourceText,
		&i.LocationHint,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComplianceTask = `-- name: GetComplianceTask :one
SELECT id, user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, completed_at,
    legal_source_url, legal_source_text, location_hint,
    metadata, created_at, updated_at
FROM compliance_tasks
WHERE id = $1 AND user_id = $2
`

type GetComplianceTaskParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetComplianceTask(ctx context.Context, arg GetComplianceTaskParams) (ComplianceTask, error) {
	row := q.db.QueryRow(ctx, getComplianceTask, arg.ID, arg.UserID)
	var i ComplianceTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaID,
		&i.RuleID,
		&i.TriggeredByEventID,
		&i.TitleEn,
		&i.TitleJa,
		&i.DescriptionEn,
		&i.DescriptionJa,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.LegalSourceUrl,
		&i.LegalSourceText,
		&i.LocationHint,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTasksForUser = `-- name: ListAllTasksForUser :many
SELECT id, user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, completed_at,
    legal_source_url, legal_source_text, location_hint,
    metadata, created_at, updated_at
FROM compliance_tasks
WHERE user_id = $1
ORDER BY
    CASE WHEN deadline_at IS NULL THEN 1 ELSE 0 END,
    deadline_at ASC,
    created_at ASC
`

func (q *Queries) ListAllTasksForUser(ctx context.Context, userID int64) ([]ComplianceTask, error) {
	rows, err := q.db.Query(ctx, listAllTasksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceTask{}
	for rows.Next() {
		var i ComplianceTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VisaID,
			&i.RuleID,
			&i.TriggeredByEventID,
			&i.TitleEn,
			&i.TitleJa,
			&i.DescriptionEn,
			&i.DescriptionJa,
			&i.Category,
			&i.Severity,
			&i.Status,
			&i.DeadlineAt,
			&i.CompletedAt,
			&i.LegalSourceUrl,
			&i.LegalSourceText,
			&i.LocationHint,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasksForUser = `-- name: ListPendingTasksForUser :many
SELECT id, user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, completed_at,
    legal_source_url, legal_source_text, location_hint,
    metadata, created_at, updated_at
FROM compliance_tasks
WHERE user_id = $1 AND status IN ('pending', 'in_progress', 'overdue')
ORDER BY
    CASE WHEN deadline_at IS NULL THEN 1 ELSE 0 END,
    deadline_at ASC,
    created_at ASC
`

func (q *Queries) ListPendingTasksForUser(ctx context.Context, userID int64) ([]ComplianceTask, error) {
	rows, err := q.db.Query(ctx, listPendingTasksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceTask{}
	for rows.Next() {
		var i ComplianceTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VisaID,
			&i.RuleID,
			&i.TriggeredByEventID,
			&i.TitleEn,
			&i.TitleJa,
			&i.DescriptionEn,
			&i.DescriptionJa,
			&i.Category,
			&i.Severity,
			&i.Status,
			&i.DeadlineAt,
			&i.CompletedAt,
			&i.LegalSourceUrl,
			&i.LegalSourceText,
			&i.LocationHint,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksTriggeredByEvent = `-- name: ListTasksTriggeredByEvent :many
SELECT id, user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, completed_at,
    legal_source_url, legal_source_text, location_hint,
    metadata, created_at, updated_at
FROM compliance_tasks
WHERE user_id = $1 AND triggered_by_event_id = $2
ORDER BY
    CASE WHEN deadline_at IS NULL THEN 1 ELSE 0 END,
    deadline_at ASC,
    created_at ASC
`

type ListTasksTriggeredByEventParams struct {
	UserID             int64       `json:"user_id"`
	TriggeredByEventID pgtype.Int8 `json:"triggered_by_event_id"`
}

// Returns tasks created by a specific life event. Used by the service layer
// to return the freshly-generated tasks from RecordLifeEvent, so the HTTP
// response can echo what was created without a follow-up query.
func (q *Queries) ListTasksTriggeredByEvent(ctx context.Context, arg ListTasksTriggeredByEventParams) ([]ComplianceTask, error) {
	rows, err := q.db.Query(ctx, listTasksTriggeredByEvent, arg.UserID, arg.TriggeredByEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceTask{}
	for rows.Next() {
		var i ComplianceTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VisaID,
			&i.RuleID,
			&i.TriggeredByEventID,
			&i.TitleEn,
			&i.TitleJa,
			&i.DescriptionEn,
			&i.DescriptionJa,
			&i.Category,
			&i.Severity,
			&i.Status,
			&i.DeadlineAt,
			&i.CompletedAt,
			&i.LegalSourceUrl,
			&i.LegalSourceText,
			&i.LocationHint,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskDone = `-- name: MarkTaskDone :one
UPDATE compliance_tasks
SET status = 'done', completed_at = NOW()
WHERE id = $1 AND user_id = $2 AND status != 'done'
RETURNING id, user_id, visa_id, rule_id, triggered_by_event_id,
    title_en, title_ja, description_en, description_ja,
    category, severity, status,
    deadline_at, completed_at,
    legal_source_url, legal_source_text, location_hint,
    metadata, created_at, updated_at
`

type MarkTaskDoneParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) (ComplianceTask, error) {
	row := q.db.QueryRow(ctx, markTaskDone, arg.ID, arg.UserID)
	var i ComplianceTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaID,
		&i.RuleID,
		&i.TriggeredByEventID,
		&i.TitleEn,
		&i.TitleJa,
		&i.DescriptionEn,
		&i.DescriptionJa,
		&i.Category,
		&i.Severity,
		&i.Status,
		&i.DeadlineAt,
		&i.CompletedAt,
		&i.LegalSourceUrl,
		&i.LegalSourceText,
		&i.LocationHint,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
