// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisa = `-- name: CreateVisa :one
INSERT INTO visas (
    user_id, visa_type_code, status,
    coe_number, coe_issued_at, landed_at,
    residence_card_number, residence_card_issued_at,
    period_of_stay_months, expires_at,
    sponsor_name, sponsor_address, job_title, notes
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10,
    $11, $12, $13, $14
)
RETURNING id, user_id, visa_type_code, status,
    coe_number, coe_issued_at, landed_at,
    residence_card_number, residence_card_issued_at,
    period_of_stay_months, expires_at,
    sponsor_name, sponsor_address, job_title, notes,
    created_at, updated_at
`

type CreateVisaParams struct {
	UserID                int64       `json:"user_id"`
	VisaTypeCode          string      `json:"visa_type_code"`
	Status                string      `json:"status"`
	CoENumber             pgtype.Text `json:"coe_number"`
	CoEIssuedAt           pgtype.Date `json:"coe_issued_at"`
	LandedAt              pgtype.Date `json:"landed_at"`
	ResidenceCardNumber   pgtype.Text `json:"residence_card_number"`
	ResidenceCardIssuedAt pgtype.Date `json:"residence_card_issued_at"`
	PeriodOfStayMonths    pgtype.Int4 `json:"period_of_stay_months"`
	ExpiresAt             pgtype.Date `json:"expires_at"`
	SponsorName           pgtype.Text `json:"sponsor_name"`
	SponsorAddress        pgtype.Text `json:"sponsor_address"`
	JobTitle              pgtype.Text `json:"job_title"`
	Notes                 pgtype.Text `json:"notes"`
}

func (q *Queries) CreateVisa(ctx context.Context, arg CreateVisaParams) (Visa, error) {
	row := q.db.QueryRow(ctx, createVisa,
		arg.UserID,
		arg.VisaTypeCode,
		arg.Status,
		arg.CoENumber,
		arg.CoEIssuedAt,
		arg.LandedAt,
		arg.ResidenceCardNumber,
		arg.ResidenceCardIssuedAt,
		arg.PeriodOfStayMonths,
		arg.ExpiresAt,
		arg.SponsorName,
		arg.SponsorAddress,
		arg.JobTitle,
		arg.Notes,
	)
	var i Visa
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaTypeCode,
		&i.Status,
		&i.CoENumber,
		&i.CoEIssuedAt,
		&i.LandedAt,
		&i.ResidenceCardNumber,
		&i.ResidenceCardIssuedAt,
		&i.PeriodOfStayMonths,
		&i.ExpiresAt,
		&i.SponsorName,
		&i.SponsorAddress,
		&i.JobTitle,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveVisaForUser = `-- name: GetActiveVisaForUser :one
SELECT
    id, user_id, visa_type_code, status,
    coe_number, coe_issued_at, landed_at,
    residence_card_number, residence_card_issued_at,
    period_of_stay_months, expires_at,
    sponsor_name, sponsor_address, job_title, notes,
    created_at, updated_at
FROM visas
WHERE user_id = $1
ORDER BY
    CASE status
        WHEN 'active' THEN 1
        WHEN 'landed' THEN 2
        WHEN 'renewal_window' THEN 3
        WHEN 'approved' THEN 4
        WHEN 'applied' THEN 5
        WHEN 'planning' THEN 6
        ELSE 99
    END,
    created_at DESC
LIMIT 1
`

// Returns the user's most relevant in-progress or active visa.
// Order prefers active/landed status over planning/applied.
func (q *Queries) GetActiveVisaForUser(ctx context.Context, userID int64) (Visa, error) {
	row := q.db.QueryRow(ctx, getActiveVisaForUser, userID)
	var i Visa
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaTypeCode,
		&i.Status,
		&i.CoENumber,
		&i.CoEIssuedAt,
		&i.LandedAt,
		&i.ResidenceCardNumber,
		&i.ResidenceCardIssuedAt,
		&i.PeriodOfStayMonths,
		&i.ExpiresAt,
		&i.SponsorName,
		&i.SponsorAddress,
		&i.JobTitle,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisaByID = `-- name: GetVisaByID :one
SELECT
    id, user_id, visa_type_code, status,
    coe_number, coe_issued_at, landed_at,
    residence_card_number, residence_card_issued_at,
    period_of_stay_months, expires_at,
    sponsor_name, sponsor_address, job_title, notes,
    created_at, updated_at
FROM visas
WHERE id = $1 AND user_id = $2
`

type GetVisaByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetVisaByID(ctx context.Context, arg GetVisaByIDParams) (Visa, error) {
	row := q.db.QueryRow(ctx, getVisaByID, arg.ID, arg.UserID)
	var i Visa
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VisaTypeCode,
		&i.Status,
		&i.CoENumber,
		&i.CoEIssuedAt,
		&i.LandedAt,
		&i.ResidenceCardNumber,
		&i.ResidenceCardIssuedAt,
		&i.PeriodOfStayMonths,
		&i.ExpiresAt,
		&i.SponsorName,
		&i.SponsorAddress,
		&i.JobTitle,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVisasForUser = `-- name: ListVisasForUser :many
SELECT
    id, user_id, visa_type_code, status,
    coe_number, coe_issued_at, landed_at,
    residence_card_number, residence_card_issued_at,
    period_of_stay_months, expires_at,
    sponsor_name, sponsor_address, job_title, notes,
    created_at, updated_at
FROM visas
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVisasForUser(ctx context.Context, userID int64) ([]Visa, error) {
	rows, err := q.db.Query(ctx, listVisasForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visa{}
	for rows.Next() {
		var i Visa
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VisaTypeCode,
			&i.Status,
			&i.CoENumber,
			&i.CoEIssuedAt,
			&i.LandedAt,
			&i.ResidenceCardNumber,
			&i.ResidenceCardIssuedAt,
			&i.PeriodOfStayMonths,
			&i.ExpiresAt,
			&i.SponsorName,
			&i.SponsorAddress,
			&i.JobTitle,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
