// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visa_types.sql

package sqlc

import (
	"context"
)

const getVisaType = `-- name: GetVisaType :one
SELECT code, display_name_en, display_name_ja, rule_file
FROM visa_types
WHERE code = $1
`

func (q *Queries) GetVisaType(ctx context.Context, code string) (VisaType, error) {
	row := q.db.QueryRow(ctx, getVisaType, code)
	var i VisaType
	err := row.Scan(
		&i.Code,
		&i.DisplayNameEn,
		&i.DisplayNameJa,
		&i.RuleFile,
	)
	return i, err
}

const listVisaTypes = `-- name: ListVisaTypes :many
SELECT code, display_name_en, display_name_ja, rule_file
FROM visa_types
ORDER BY code
`

func (q *Queries) ListVisaTypes(ctx context.Context) ([]VisaType, error) {
	rows, err := q.db.Query(ctx, listVisaTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VisaType{}
	for rows.Next() {
		var i VisaType
		if err := rows.Scan(
			&i.Code,
			&i.DisplayNameEn,
			&i.DisplayNameJa,
			&i.RuleFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
